[package]
name = "verification-ea"
version = "0.1.0"
edition = "2021"

[dependencies]
bellpepper-core = "0.4.0"
nova-snark = "0.37.0"
rand = "0.8.5"
rocket = {version = "0.5.1", features = ["json"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
