[package]
name = "aggproof"
version = "0.1.0"
edition = "2021"

[dependencies]
bellpepper-core = "0.4.0"
bincode = "1.3.3"
flate2 = "1.0.31"
nova-snark = "0.37.0"
rand = "0.8.5"
serde_json = "1.0.125"
