version: '2'

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.5.0
        command: launch manager
        environment:
         - CALIPER_PROJECTCONFIG=TaskManagement/config/caliper-onchain.yml
         - CALIPER_BIND_SUT=besu:latest
         - CALIPER_BENCHCONFIG=TaskManagement/config/caliper-benchconfig.yml
         - CALIPER_NETWORKCONFIG=TaskManagement/config/caliper-networkconfig.json 
         - CALIPER_FLOW_SKIP_INSTALL=true
        volumes:
         - .:/hyperledger/caliper/workspace
        network_mode: host
